### ISSUE TITLE
Update nodes to allow radio creation and selection

### ISSUE THREAD

**Issue by njungels** [stephenhouser/node-red-contrib-flexradio#35]
First, thanks for the work. I find it very interesting. I've just started to use this, so let me know if this is already possible, or is an impossible ask.

When multiple radios are on the network, a nice enhancement would be to allow the creation of the radio connection and then use that as the connection in downstream nodes. 

This flow is modified from your multiple radio discovery flow:
![image](https://user-images.githubusercontent.com/2224574/150641907-081a6584-9e48-4e52-b7e5-2a6baf3802cc.png)

Which produces this dashboard:
![image](https://user-images.githubusercontent.com/2224574/150641938-277ba9cb-63ce-497a-a9e9-c0a6bd26eba0.png)
(note the blank button is because the second radio does not have a name)

The intent is that once the radio of interest is selected, it would send a message to a connection object and other flows would then be able to use that radio connection.

My personal end use case would be to connect to a specific radio. I would like to display all of the meters (and I mean _all_ of them) for testing.

**Comment by stephenhouser** [comment]
I suspect this might be easily added with the recent (month ago) changes I made to the flexradio-radio configuration node which allows dynamic configuration. I just need to sort out which node this configuration would be sent into as the -radio node is not exposed on the dashboard.

**Comment by stephenhouser** [comment]
Initial thoughts. I think this also encompasses the request in #34.

- request node
    `msg.action = connect | disconnect`

    connect will need a radio to connect to: `msg.radio = { host: '...', port: '...' }` a.k.a. manual or `{ nickname: '...' }` from discovery

- stream node  
    Action = Subscribe to stream | Dynamic subscription

    - if `subscribe`, show topic field and use as normal
    - if `dyanmic` hide topic and
       - show input connector
       - msg.action = subscribe | unsubscribe
       -  msg.topic = stream id to subscribe or unsubscribe from

- meter node
    Action = Subscribe to meter | Dynamic subscription
    - if `subscribe` show topic field and use as normal
    - if `dyanmic` hide topic and...
        - show input connector
        - msg.action = subscribe | unsubscribe
        - msg.topic = meter to subscribe or unsubscribe from

- messages node
  Something similar? This is really an output only node, but some filtering might be nice.

- discovery node
  Some filtering out output might be nice, so show discovery data from only a single radio. This was requested in #36

**Comment by stephenhouser** [comment]
Resolved in 1feaadbfd81898c45a46c9f9f970d077c5ca64e7 (v1.2)
