### ISSUE TITLE
Catch errors on failed connections to radio

### ISSUE THREAD

**Issue by stephenhouser** [stephenhouser/node-red-contrib-flexradio#37]
Throw proper node-red errors to enable catching on failed connection attempts. Enable host unreachable error to be managed (or eaten). Occurs when the target radio is powered down or otherwise offline.

[from Warren]

**Comment by k5map** [comment]
You have my vote for this feature !

**Comment by stephenhouser** [comment]
With a manual or dynamic connection with a specific IP you can get EHOSTUNREACH messages. These are exposed in `flexradio-radio` config node. Should they "bubble up" to the nodes connected to them or report the error in another way.

**Comment by stephenhouser** [comment]
Finding it problematic to bubble up errors that are not generated directly by a message. Documentation suggests that config nodes can generate catchable errors, but these are all seemingly from a message that existed on a flow. In the case of generating them from the lower level, e.g. the network connection, they just don't get sent anywhere useful.
